import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import Resume from '../components/Resume';
import { FaDownload, FaShare, FaShareSquare, FaFileDownload } from 'react-icons/fa';
import styled from 'styled-components';
import { Fonts, Spacing } from '../design-system';

const HomePage: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Andrew Gnott: Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DownloadLink href="/agnott-resume-2022-01-19.pdf">
        <FaFileDownload />
      </DownloadLink>
      <Resume hideHeader />
    </React.Fragment>
  );
};

const DownloadLink = styled.a`
  ${Fonts.bold[400]}
  position: absolute;
  right: ${Spacing.em.xxxSmall};
  transform: translateY(${Spacing.em.xxxSmall});
`;

export default HomePage;
