import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import Resume from '../components/Resume';

const HomePage: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Andrew Gnott: Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Resume hideHeader />
    </React.Fragment>
  );
};

export default HomePage;
