import Head from 'next/head';
import React, { useState } from 'react';
import type { NextPage } from 'next';
import styled, { keyframes } from 'styled-components';
import { Colors, Fonts, Shadows, Spacing } from '../design-system';
import { Page } from '../design-system/components/Layout';

const RightContent = styled.div`
  padding: ${Spacing.large}px;
`;

const AccentImage = styled.svg`
  position: absolute;
  bottom: ${Spacing.xxSmall}px;
  right: ${Spacing.xxSmall}px;
  fill: ${Colors.solids.raisinBlack};
  fill-rule: evenodd;
  clip-rule: evenodd;
  stroke-linejoin: round;
  stroke-miterlimit: 2;
`;

const Resume: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Andrew Gnott</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RightContent>crap</RightContent>
    </React.Fragment>
  );
};

export default Resume;
