import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import Resume from '../components/Resume';
import styled from 'styled-components';
import { Colors, Spacing } from '../design-system';

const ResumePage: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Andrew Gnott: Resume</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ResumeContainer>
        <Resume />
      </ResumeContainer>
    </React.Fragment>
  );
};

export default ResumePage;

const ResumeContainer = styled.div`
  background-color: ${Colors.solids.oldLace};
  padding: ${Spacing.small}px;
`;
